### ISSUE TITLE
Fix `/undefined` routing from webpack-dev-server

### ISSUE THREAD

**Issue by nwaywood** [nwaywood/react-fullstack-template#5]
The package.json file hasn't changed, therefore a ^ change of something must have broken this.

Since npm 5 supports lockfiles now, I think when we fix this issue we should commit the lockfile so this doesn't happen again.

**Comment by nwaywood** [comment]
There is now an open issue for this here https://github.com/webpack/webpack-dev-server/issues/972
From that issue it can be seen that we can fix this now by adding the openPage option like so:

```
devServer: {
  open: true,
  openPage: ""
}
```

But I reckon we leave it since it will be resolved once that issue is fixed.

**Comment by dainyl** [comment]
Fixed by current webpack version
